- name: install apache on webservers
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"
    state: latest

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: ensure apache is running
  tags: apache,ubuntu
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
          
- name: copy html file for site
  tags: apache,fedora
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin example@example.com
  when: ansible_distribution == "Fedora"
  notify: restart_apache


