---
- hosts: all
  become: true
  tasks:

  - name: install apache and supporting php packages 
    ansible.builtin.package:
      update_cache: yes
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

