---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Fedora
    ansible.builtin.dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates for Ubuntu
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: us
  become: true
  tasks:

    - name: install apache on the webservers
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: fs
  become: true
  tasks:
    - name: install mariadb on db servers
      ansible.builtin.dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"

