---
- hosts: all
  become: true
  tasks:

  - name: install apache2 and supporting php packages 
    ansible.builtin.apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and supporting php packages
    ansible.builtin.dnf:
      update_cache: yes
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
