---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Fedora
    tags: always
    ansible.builtin.dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: create user
    tags: always
    ansible.builtin.user:
      name: simone
      groups: root

  - name: add sudoers file
    tags: always
    ansible.builtin.copy:
      src: nopasswd
      dest: /etc/sudoers.d/nopasswd
      owner: root
      group: root
      mode: 0440

  - name: add ssh key
    tags: always
    ansible.builtin.authorized_key:
      user: n
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQJiBJ3gKBhu0rtY1gqNLeZqUrl1BzkBdQnaJLJjN/a thenickstrick"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache on the webservers (ubuntu)
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy html file for site
      tags: apache,ubuntu
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: ensure apache is running (ubuntu)
      tags: apache,ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
          
    - name: install apache on the webservers (fedora)
      tags: apache,fedora
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Fedora"

    - name: copy html file for site
      tags: apache,fedora
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: ensure apache is running (fedora)
      tags: apache,fedora
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_distribution == "Fedora"

    - name: change email address for admin
      tags: apache,fedora
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin example@example.com
      when: ansible_distribution == "Fedora"
      register: httpd

    - name: restart httpd (fedora)
      tags: agache,fedora
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: httpd.changed

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb on db servers
      tags: db,fedora
      ansible.builtin.dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"

