---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 package
    ansible.builtin.apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ununtu"

  - name: remove support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: remove httpd package
    ansible.builtin.dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "Fedora"

  - name: remove php support for apache
    ansible.builtin.dnf:
      name: php
      state: absent
    when: ansible_distribution == "Fedora"
