---
- hosts: all
  become: true
  tasks:

  - name: remove apache2 and php packages
    ansible.builtin.apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove httpd and php packags
    ansible.builtin.dnf:
      update_cache: yes
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution == "Fedora"

