---
- hosts: all
  become: true
  tasks:

  - name: remove apache and php packages
    ansible.builtin.package:
      update_cache: yes
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent

